---
- hosts: localhost
  connection: local
  vars_files:
    - group_vars/vars/lab_vc_avi_variables.yml
    - group_vars/vault/lab_vc_vault.yml
  roles:
    - { role: avinetworks.avicontroller-vmware }
    - { role: avinetworks.avisdk }
  tasks:
    - name: Create Cloud VCUSER user
      avi_api_session:
        controller: "{{ controller_cluster_vip }}"
        username: "{{ avi_credentials.username }}"
        password: "{{ avi_credentials.password }}"
        http_method: post
        path: "cloudconnectoruser"
        api_version: '20.1.1'
        data:
          vcenter_credentials:
                username: "{{ vcenter_user }}"
                password: "{{ vcenter_password }}"
          name: "{{ avi_vmware_cloudname }}"
    - name: Create Nsxt user
      avi_api_session:
        controller: "{{ controller_cluster_vip }}"
        username: "{{ avi_credentials.username }}"
        password: "{{ avi_credentials.password }}"
        http_method: post
        path: "cloudconnectoruser"
        api_version: '20.1.1'
        data:
          nsxt_credentials:
                username: "{{ nsxt_user }}"
                password: "{{ nsxt_password }}"
          name: "{{ avi_nsxt_cloudname }}"