---
- hosts: localhost
  connection: local
  vars_files:
    - group_vars/vars/lab_vc_avi_variables.yml
    - group_vars/vault/lab_vc_vault.yml
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: Cloud Connector Configuration
      avi_cloud:
        api_version: '20.1.6'
        name: "{{ avi_vm_nsxr_cloud_name }}"
        controller: "{{ controller_cluster_vip }}"
        username: "{{ avi_credentials.username }}"
        password: "{{ avi_credentials.password }}"
        obj_name_prefix: 'lab-vc-'
        vtype: CLOUD_NSXT # Cloud Options CLOUD_NONE, CLOUD_VCENTER, CLOUD_OPENSTACK, CLOUD_AWS, CLOUD_VCA, CLOUD_APIC, CLOUD_MESOS, CLOUD_LINUXSERVER, CLOUD_DOCKER_UCP, CLOUD_RANCHER, CLOUD_OSHIFT_K8S, CLOUD_AZURE, CLOUD_GCP, CLOUD_NSXT
        dhcp_enabled: false
        license_type: "LIC_CORES"
        uuid: 'cloud-1d1485d3-fa1c-4e04-b347-49ea156010c0'
        nsxt_configuration:
          nsxt_credentials_ref: "cloudconnectoruser-a4854859-5734-42f2-9c11-c0113de9ca27" #Credentials to access NSX-T manager. It is a reference to an object of type CloudConnectorUser
          nsxt_url: '172.16.1.21' #NSX-T manager hostname or IP address
          management_network_config:
              overlay_segment:
                segment_id: '/infra/segments/pg-seg-10041'
                tier1_lr_id: '/infra/tier-1s/T1-AVI-MGT' #Tier1 logical router path. Example- /infra/tier-1s/T1-01
              transport_zone: '/infra/sites/default/enforcement-points/default/transport-zones/0bba80c6-efa6-4c82-a97c-0ad722839e55'
              tz_type: 'OVERLAY'
          data_network_config:
            tz_type: 'OVERLAY'
            transport_zone: '/infra/sites/default/enforcement-points/default/transport-zones/0bba80c6-efa6-4c82-a97c-0ad722839e55'
            tier1_segment_config:
              segment_config_mode: 'TIER1_SEGMENT_MANUAL'
              #manual:
              tier1_lr_id: '/infra/tier-1s/T1-LAB-VC-DC01-01'
              segment_id: '/infra/segments/pg-seg-10001'
          avi_vcenterserver:
            content_lib: '5c959cac-fb70-437f-9bf3-1fb444e1727b'
            name: 'lab-vc-vcsa01'
            #tenant_ref: "{{ item.tenant_ref | default(omit) }}"
            uuid: 'https://172.16.1.150/api/cloud/cloud-1d1485d3-fa1c-4e04-b347-49ea156010c0'
            vcenter_credentials_ref: 'lab-vcsa-user'
            vcenter_url: '192.168.1.20'
