# ovftool is part of the SDK
ovftool_path: /usr/lib/vmware-ovftool

# downloaded OVA location
ova_path: /home/garethl/.ansible/playbooks/files/controller-20.1.6-9132.ova

#Datacenter to use
datacenter: MK19

# Cluster Name
cluster: lab-vc-workload

# Network for the Avi Mgmt
mgmt_network:  'pg-mgt-vlan-401'

# Turn on the VM after the push
power_on: true

#Which  inventory info do I use
mycloud: home

# Folder where to push the Avi Controller
vcenter_folder: vmware/avi

# Number of CPU Min 8
number_of_cpus: 8

# RAM for the Avi Controller min 24
memory: 24

# Password used in the playbook which is in your vault
password: 'F1ghtZclub!'

# Old password of Avi Controller this is in the Avi Portal
old_password: '58NFaGDJm(PJH0G'

# the email you want to use for the Avi
avi_email: gareth.llewellyn@vcumulus.lab

# Default admin tenant in Avi
username: admin

# API version
api_version: 18.2.7

# Domain to search for the Avi Controller
search_domains: vcumulus.lab

# DNS servers
dns_server01: 172.16.1.2
dns_server02: 172.16.1.3
# NTP Servers
ntp_server01: 192.168.1.13
ntp_server02: 192.168.1.14

#Portal UI Display Banner and MOTD
banner_txt: "Deployed by vCumulus Limited"
motd_welcome: 
ctl1: true

## Controllers
controller1:
   - name: lab-vc-avict01
     mgmt_ip:  172.16.1.151
     mgmt_mask: 255.255.255.0
     default_gw: 172.16.1.1
     password: 'F1ghtZclub!'
controller2:
   - name: lab-vc-avict02
     mgmt_ip: 172.16.1.152
     mgmt_mask: 255.255.0.0
     default_gw: 172.16.1.1
     ctl: no
controller3:
   - name: lab-vc-avict03
     mgmt_ip: 172.16.1.153
     mgmt_mask: 255.255.255.0
     default_gw: 172.16.1.1
     ctl: no

# vsphere
vcenter:
  vcenter_url: 192.168.1.20
  username: 'administrator@vsphere.local'
  password: 'VMware1!VMware1!'
  datacenter: 'MK19'
  network_mgmt: pg-mgt-vlan-401

# Avi info used in the script
avi_credentials:
  controller: 172.16.1.151
  username: 'admin'
  password: 'F1ghtZclub!'
  api_version: '18.2.7'