---
- hosts: localhost
  connection: local
  vars_files:
    - vars/default.yml
  roles:
    - role: avinetworks.avicontroller-vmware
    - role: avinetworks.avisdk
    - role: avinetworks.aviconfig
  gather_facts: false
  tasks:
    - name: Deploy Avi Controllers
      deploy_controller:
        state: present
        ovftool_path: '{{ ovftool_path }}'
        vcenter_host: '{{ vcenter.vcenter_url }}'
        vcenter_user: '{{ vcenter.username }}'
        vcenter_password: '{{ vcenter.password }}'
        con_datacenter: '{{ datacenter }}'
        con_cluster: '{{ cluster }}'
        con_datastore: '{{ datastore | default(omit) }}'
        con_disk_mode: '{{ disk_mode | default(omit) }}'
        con_mgmt_network: '{{ mgmt_network }}'
        con_ova_path: '{{ ova_path }}'
        con_power_on: '{{ power_on }}'
        con_vcenter_folder: '{{ vcenter_folder }}'
        con_disk_size: '{{ disk_size | default(omit) }}'
        con_vm_name: '{{ item.name }}'
        con_mgmt_ip: '{{ item.mgmt_ip }}'
        con_mgmt_mask: '{{ item.mgmt_mask}}'
        con_default_gw: '{{ item.default_gw }}'
      no_log: false
      with_items:
        - "{{ controller1 }}"
        - "{{ controller2 }}"
        - "{{ controller3 }}"
      tags:
        - avicontrollers